version: '3.8'

services:
  web:
    restart: always
    environment:
      - FLASK_ENV=production
      - MONGODB_URI=mongodb://smartrade:smartradeProd@mongo_db:27017
    ports:
      - 5050:5001

  mongodb:
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=smartrade
      - MONGO_INITDB_ROOT_PASSWORD=smartradeProd
    ports:
      - 27019:27017
    volumes:
      - mongo-data-prod:/data/db

volumes:
  mongo-data-prod:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /usr/local/mongodb