version: '3.8'

services:
  flask:
    container_name: flask_server
    build: .
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5001
      - FLASK_APP=smartrade
      - FLASK_CONF_PATH=/app/config.yml 
      - TRADE_DATA=/app
    volumes:
      - log:/var/log/smartrade
    links:
      - mongodb

  mongodb:
    container_name: mongo_db
    image: mongo:4.4.5
    command: ['--logpath', '/var/log/mongodb/mongod.log']
    volumes:
      - log:/var/log/mongodb

volumes:
  log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/log/smartrade
