version: '3.8'

services:
  flask:
    restart: always
    environment:
      - FLASK_ENV=production
      - MONGODB_URI=mongodb://smartrade:smartradeProd@mongo_db:27017
    command: gunicorn -w 1 -b 0.0.0.0:8000 smartrade.wsgi:app
    build:
      args:
        ENV: production

  mongodb:
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=smartrade
      - MONGO_INITDB_ROOT_PASSWORD=smartradeProd
    ports:
      - 27019:27017
    volumes:
      - mongo-data-prod:/data/db

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - 5050:80
    volumes:
      - log:/var/log/nginx
    depends_on:
      - flask

volumes:
  mongo-data-prod:
    driver: local
    driver_opts:
      type: none
      o: bind
      #device: tmp/data-prod
      device: /usr/local/mongodb
